# Configuration for Niche Finder Lambda function

# AWS resources
s3_bucket_name: "niche-finder"  # Replace with actual S3 bucket name
sqs_queue_name: "niche-finder"  # Replace with actual SQS queue name
topic_name: "niche-finder"  # Replace with actual SNS topic name
cloudwatch_schedule_expression: "cron(0 * * * ? *)"  # Every hour (replace as needed)
visibility_timeout: 300 # Visibility timeout for SQS messages

# Notification details
phone_number: "+610406252420"  # Replace with actual phone number
email_address: "mfawsaibot@gmail.com"  # Replace with actual email address

# Add other configuration parameters as needed
api_key: "your-gemini-api-key"  # Example for a hypothetical API key
api_endpoint: "https://<region>.vertexai.google/v1/projects/<project-id>/locations/<location>/models/<model-id>:generate" # Example for a hypothetical API endpoint

# ... other configuration options

#table names
table_names:
  niche-finder: "niche-finder" 
  affiliate_program: "affiliate-program"
  subscription_service_cost: "subscription-service-cost"
  campaign: "campaign"
  campaign_content: "campaign-content"
  campaign_metrics: "campaign-metrics"

#topic names
topic_names:
  affiliate_program: "affiliate-program"
  campaign: "campaign"
  campaign_content: "campaign-content"
  campaign_metrics: "campaign-metrics"

#Queue Configs
queue_configs:
  affiliate_program:
    name: affiliate-program
    visibility_timeout: 300
  campaign:
    name: campaign
    visibility_timeout: 300
  campaign_content:
    name: campaign-content
    visibility_timeout: 300
  campaign_metrics:
    name: campaign-metrics
    visibility_timeout: 300

#data stream names
data_stream_name: "data-stream"

  