# AWS Resources Configurations

# Bucket names
bucket_names:
  data-stream-bucket: "data-stream-bucket"
  niche-finder-bucket: "niche-finder-bucket" 
  affiliate-program-bucket: "affiliate-program-bucket"
  sub-service-cost-_bucket: "sub-service-cost-bucket"
  campaign-bucket: "campaign-bucket"
  campaign-content-bucket: "campaign-content-bucket"
  campaign-metrics-bucket: "campaign-metrics-bucket"


# Table names
table_names:
  niche-finder-table: "niche-finder-table" 
  affiliate_program-table: "affiliate_program-table"
  sub-service-cost-_table: "sub-service-cost-table"
  campaign-table: "campaign-table"
  campaign_content-table: "campaign_content-table"
  campaign_metrics-table: "campaign_metrics-table"

# Topic names
topic_names:
  niche-finder-topic: "niche-finder-topic"
  affiliate_program-topic: "affiliate_program-topic"
  campaign-topic: "campaign-topic"
  campaign_content-topic: "campaign_content-topic"
  campaign_metrics-topic: "campaign_metrics-topic"

# Queue Configs
queue_configs:
  niche-finder-queue:
    name: niche-finder-queue
    visibility_timeout: 300
  affiliate_program-queue:
    name: affiliate_program-queue
    visibility_timeout: 300
  campaign-queue:
    name: campaign-queue
    visibility_timeout: 300
  campaign_content-queue:
    name: campaign_content-queue
    visibility_timeout: 300
  campaign_metrics-queue:
    name: campaign_metrics-queue
    visibility_timeout: 300

# Data stream names
data-stream-name: "data-stream"

# Log Group Names
log_group_name: "main-infrastructure-log-group"
